### PR TITLE
FIX README

### PR DESCRIPTION
**Pull request by easy-Coder**
I fixed two typos i find on the readme file. I also fix the folder structure section to be more readable

### CODE REVIEW

**Comment by edemekong** [comment]
this looks good @easy-Coder... you are very welcome to contribute more... thanks!

**Comment by easy-Coder** [comment]
> this looks good @easy-Coder... you are very welcome to contribute more... thanks!

I really want to contribute more. But I am thinking is there a way to know the features you have in mind for the project and also the ui design you follow. Thanks

**Comment by edemekong** [comment]
Currently there is no ui design... but we can definitely hop on a call maybe next week, see how can we move forward with improving existing features only. :)

**Comment by easy-Coder** [comment]
Okay sounds good

**Comment by edemekong** [comment]
> Okay sounds good

hey, will you be available tomorrow. to discuss over this project?

**Pull request merged**
